[sz]

grpc_server = "localhost:8261"
er_path = "data/er.json"
thesaurus_path = "data/thesaurus.ttl"

[erkg]

erkg_path = "data/erkg.json"

[ctx]

domain_class = "DomainContext"
domain_bundle = "domain.json"

[nlp]

parser_class = "Parser"
spacy_model = "en_core_web_md"
lex_path = "data/lex.json"
#gliner_model = "urchade/gliner_medium-v2.1"
gliner_model = "urchade/gliner_small-v2.1"
chunk_size = 1000

[tr]

tr_alpha = 0.85
tr_lookback = 3

[ent]

store_path = "data/ent.json"
vec_path = "data/ent.vec"
w2v_path = "data/ent.w2v"

[vect]

lancedb_uri = "data/lancedb"
chunk_table = "chunk"
chunk_size = 1024
fts_column = "text"

[scraper]

cache_expire = 604800
cache_path = "data/url_cache"

[vis]

html_path = "data/erkg.html"
html_height = "900px"
html_width = "100%"

[rag]

lm_name = "ollama_chat/gemma3:12b"
api_base = "http://localhost:11434"
temperature = 0.0
max_tokens = 3000
max_chunks = 11
num_perm = 128
lsh_top_k_question = 9
lsh_top_k_lemma = 3
w2v_top_k = 20
w2v_min_dist = 0.33

[opik]

base_url = "http://localhost:5173/api"

[prof]

use_pyinst = false
