[nlp]

spacy_model = "en_core_web_md"
gliner_model = "urchade/gliner_medium-v2.1"

[scraper]

cache_path = "data/url_cache"
cache_expire = 604800

[ent]

w2v_path = "data/entity.w2v"

[vect]

lancedb_uri = "data/lancedb"
chunk_table = "chunk"
chunk_size = 1024
fts_column = "text"

[tr]

tr_alpha = 0.85
tr_lookback = 3

[kg]

domain_path = "domain.ttl"
kg_path = "data/kg.json"
html_path = "kg.html"

[vis]

html_height = "900px"
html_width = "100%"

[rag]

num_chunks = 11
