[project]

name = "strwythura"
version = "0.2.0"
description = "Tutorial for how to construct knowledge graphs from unstructured data sources"

authors = [
    { name = "Paco Nathan", email = "paco@derwen.ai"}
]

readme = "README.md"
license = { text = "MIT" }

requires-python = ">=3.11,<3.12"

dependencies = [
    "gliner (>=0.2.21,<0.3.0)",
    "gliner-spacy (>=0.0.11,<0.0.12)",
    "icecream (>=2.1.5,<3.0.0)",
    "ipywidgets (>=8.1.7,<9.0.0)",
    "spacy (>=3.8.7,<4.0.0)",
    "jupyterlab (>=4.4.5,<5.0.0)",
    "jupyterlab-execute-time (>=3.2.0,<4.0.0)",
    "networkx (>=3.5,<4.0)",
    "pyinstrument (>=5.0.3,<6.0.0)",
    "pyvis (>=0.3.2,<0.4.0)",
    "requests (>=2.32.4,<3.0.0)",
    "tqdm (>=4.67.1,<5.0.0)",
    "watermark (>=2.5.0,<3.0.0)",
    "datasets (>=4.0.0,<5.0.0)",
    "gensim (>=4.3.3,<5.0.0)",
    "lancedb (>=0.24.2,<0.25.0)",
    "loguru (>=0.7.3,<0.8.0)",
    "lxml (>=6.0.0,<7.0.0)",
    "ipython (>=9.4.0,<10.0.0)",
    "nltk (>=3.9.1,<4.0.0)",
    "bs4 (>=0.0.2,<0.0.3)",
    "ollama (>=0.5.1,<0.6.0)",
    "baml-cli (>=0.1.0,<0.2.0)",
    "glirel @ git+https://github.com/ceteri/GLiREL.git",
]


[build-system]

requires = [
    "poetry-core>=2.0.0,<3.0.0"
]

build-backend = "poetry.core.masonry.api"
